version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: carecall-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carecall
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d carecall"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: carecall_postgres_data 